# Generated by Django 6.0.5 on 2026-05-21 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomCheker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('duration_of_symptoms', models.CharField(max_length=50)),
                ('symptoms', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('possible_conditions', models.TextField(blank=True, null=True)),
                ('triage_urgency', models.CharField(blank=True, max_length=20, null=True)),
                ('recommended_specialist', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
