# Generated by Django 6.0.5 on 2026-05-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doctor_license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='doctor_specialization',
            field=models.CharField(blank=True, choices=[('general_practitioner', 'General Practitioner'), ('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('neurologist', 'Neurologist'), ('pediatrician', 'Pediatrician'), ('psychiatrist', 'Psychiatrist'), ('oncologist', 'Oncologist'), ('surgeon', 'Surgeon'), ('orthopedic', 'Orthopedic'), ('gynecologist', 'Gynecologist'), ('urologist', 'Urologist')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='doctor_years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
