# Generated by Django 6.0.5 on 2026-05-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_doctor_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doctor_price_per_session',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
